server:
  port: "8080"
database:
  mongo:
    connection:
      text: "mongodb://localhost:27017/?serverSelectionTimeoutMS=5000&connectTimeoutMS=10000&3t.uriVersion=3&3t.connection.name=go&3t.alwaysShowAuthDB=true&3t.alwaysShowDBFromUserRole=true"